version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    pull_policy: "build"
    image: portal_workflow
    environment:
      - TZ=Asia/Bangkok
    ports:
      - 8088:8080
    restart: unless-stopped
