"use client";

import { signIn, signOut, useSession } from "next-auth/react";

import Head from "next/head";
import Link from "next/link";

export default function HomePage({ children }: { children: React.ReactNode }) {
  // const { data: session } = useSession();
  return <>sdsad</>
  // if (session) {
  //   return (
  //     <>
  //       Signed in as {JSON.stringify(session)} <br />
  //       <button onClick={() => signOut()}>Sign out</button>
  //       {children}
  //     </>
  //   );
  // }

  // return (
  //   <>
  //     <Head>
  //       <title>Create Next App</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <meta name="viewport" content="width=device-width, initial-scale=1" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>
  //     <main>
  //       Not signed in <br />
  //       <Link href='/login'>
  //         <button>Sign in</button>
  //       </Link>
  //       <h1 className=" text-red-400">asdasmldashdgashdgh</h1>
  //     </main>
  //   </>
  // );
}
